name: Mod CI Build

on:
  push:
    branches: [ "C-M-Y" ]
  pull_request:
    branches: [ "C-M-Y" ]
  workflow_dispatch:

jobs:
  try_to_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
            ndk-version: r28
      - name: Change VersionName to Nightly Version
        run: sed -i 's/\(version=.*\) ([0-9]\{4\}\.[0-9]\{2\}\.[0-9]\{2\})/\1 (Nightly)('"$(date "+%Y-%m-%d %T")"')/' mod/source/module.prop
      - name: Setup zip
        uses: montudor/action-zip@v1
      - name: Build Mod
        run: |
          cd mod ; sh build.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CacheCleaner-Mod
          compression-level: 9
          path: mod/build/